version: '3.4'

services:
  surging.apigateway:
    image: ${DOCKER_REGISTRY}surgingapigateway
    build:
      context: .
      dockerfile: Surging.ApiGateway/Dockerfile

  surging.identity.server:
    image: ${DOCKER_REGISTRY}surgingidentityserver
    build:
      context: .
      dockerfile: Suriging.Identity/Surging.Identity.Server/Dockerfile

