<<<<<<< HEAD
version: '3.4'

services:
  surging.apigateway:
    image: ${DOCKER_REGISTRY}surgingapigateway
    build:
      context: .
      dockerfile: Surging.ApiGateway/Dockerfile

  surging.identity.server:
    image: ${DOCKER_REGISTRY}surgingidentityserver
    build:
      context: .
      dockerfile: Suriging.Identity/Surging.Identity.Server/Dockerfile

=======
version: '3'

services:
  surging.apigateway:
    image: ${DOCKER_REGISTRY}surgingapi
    ports:
      - 729:729
    environment:
      Register_Conn:"192.168.72.129:8500"
    build:
      context: .
      dockerfile: Surging.ApiGateway/Dockerfile
>>>>>>> upstream/master
